### Создать клиента
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "name": "Abylay"
}

### Создать аккаунт
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "customerId": 1,
  "balance": 1000
}

### Получить аккаунт
GET http://localhost:8080/api/accounts/1

### Депозит
POST http://localhost:8080/api/accounts/1/deposit
Content-Type: application/json

{
  "amount": 500
}

### Снятие
POST http://localhost:8080/api/accounts/1/withdraw
Content-Type: application/json

{
  "amount": 200
}